on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Code quality
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install
      - name: Build
        run: bun run build
      - name: Run linting
        run: bun run lint
      - name: Check Bundle Size
        run: bun run size-limit
      - name: Run tests
        run: bun run test:ci
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
